# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.radioButton_15 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_15.setText("")
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_5.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_16.setText("")
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_5.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_17.setText("")
        self.radioButton_17.setObjectName("radioButton_17")
        self.horizontalLayout_5.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_18.setText("")
        self.radioButton_18.setObjectName("radioButton_18")
        self.horizontalLayout_5.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_19.setText("")
        self.radioButton_19.setObjectName("radioButton_19")
        self.horizontalLayout_5.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_20.setText("")
        self.radioButton_20.setObjectName("radioButton_20")
        self.horizontalLayout_5.addWidget(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_21.setText("")
        self.radioButton_21.setObjectName("radioButton_21")
        self.horizontalLayout_5.addWidget(self.radioButton_21)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.radioButton_22 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_22.setText("")
        self.radioButton_22.setObjectName("radioButton_22")
        self.horizontalLayout_6.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_23.setText("")
        self.radioButton_23.setObjectName("radioButton_23")
        self.horizontalLayout_6.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_24.setText("")
        self.radioButton_24.setObjectName("radioButton_24")
        self.horizontalLayout_6.addWidget(self.radioButton_24)
        self.radioButton_25 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_25.setText("")
        self.radioButton_25.setObjectName("radioButton_25")
        self.horizontalLayout_6.addWidget(self.radioButton_25)
        self.radioButton_26 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_26.setText("")
        self.radioButton_26.setObjectName("radioButton_26")
        self.horizontalLayout_6.addWidget(self.radioButton_26)
        self.radioButton_27 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_27.setText("")
        self.radioButton_27.setObjectName("radioButton_27")
        self.horizontalLayout_6.addWidget(self.radioButton_27)
        self.radioButton_28 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_28.setText("")
        self.radioButton_28.setObjectName("radioButton_28")
        self.horizontalLayout_6.addWidget(self.radioButton_28)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.radioButton_8 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_4.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_4.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_10.setText("")
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_11.setText("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_4.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_12.setText("")
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_4.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_13.setText("")
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_4.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_14.setText("")
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_4.addWidget(self.radioButton_14)
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.verticalLayout.addWidget(self.widget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.label_18.setText(_translate("MainWindow", "----"))
        self.label_3.setText(_translate("MainWindow", "-3"))
        self.label_4.setText(_translate("MainWindow", "-2"))
        self.label_5.setText(_translate("MainWindow", "-1"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "2"))
        self.label_9.setText(_translate("MainWindow", "3"))
        self.label_19.setText(_translate("MainWindow", "----"))
        self.label_10.setText(_translate("MainWindow", "XX"))
        self.label_11.setText(_translate("MainWindow", "XX"))
        self.label_12.setText(_translate("MainWindow", "XX"))
        self.label_13.setText(_translate("MainWindow", "XX"))
        self.label_14.setText(_translate("MainWindow", "XX"))
        self.label_15.setText(_translate("MainWindow", "XX"))
        self.label_16.setText(_translate("MainWindow", "XX"))
        self.label_17.setText(_translate("MainWindow", "XX"))
        self.label.setText(_translate("MainWindow", "XXXX/XXXXX"))



class MainWindow(QtWidgets.QMainWindow):
    resized = QtCore.pyqtSignal()  # 窗口缩放信号
    showTextSignal = QtCore.pyqtSignal(str)  # 文字修改信号

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        # self.resized.connect(self.resize_func)

    # def resizeEvent(self, a0: QtGui.QResizeEvent) -> None:
    #     """
    #     重载resize事件
    #     :param a0:
    #     :return:
    #     """
    #     self.resized.emit()
    #     return super(MainWindow, self).resizeEvent(a0)

    # def resize_func(self):
    #     self.ui.refresh_img(result_json=self.ui.result_json)

    # def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
    #     """
    #     重载close事件
    #     :param a0:
    #     :return:
    #     """
    #     if self.ui.pushButton_Disconnect.isEnabled():
    #         self.ui.disconnect_click()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    sys.exit(app.exec_())